# Generated by Django 3.2.12 on 2022-06-10 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_title'),
        ('tickets', '0004_auto_20220610_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='movie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
